import"./assets/styles-49a2a51d.js";import{C as n}from"./assets/vendor-1e6f2856.js";const s="/apartment-renovation-new-jersey/assets/IMG_3542-3179e25a.jpg",o="/apartment-renovation-new-jersey/assets/IMG_3543-030f8f67.jpg",i="/apartment-renovation-new-jersey/assets/IMG_3544-ef55b624.jpg",r="/apartment-renovation-new-jersey/assets/IMG_3545-50475299.jpg",g="/apartment-renovation-new-jersey/assets/IMG_3546-1f42defa.jpg",c="/apartment-renovation-new-jersey/assets/IMG_3547-47ff4e04.jpg",p="/apartment-renovation-new-jersey/assets/IMG_3548-e0db446d.jpg",l="/apartment-renovation-new-jersey/assets/IMG_3549-7a70edfe.jpg",m="/apartment-renovation-new-jersey/assets/IMG_3550-3cb682f2.jpg",d="/apartment-renovation-new-jersey/assets/IMG_3551-5443b2c3.jpg",j="/apartment-renovation-new-jersey/assets/IMG_3552-8dc43dbc.jpg",y="/apartment-renovation-new-jersey/assets/IMG_3553-a48d4f17.jpg",h="/apartment-renovation-new-jersey/assets/IMG_3554-17c9ab4f.jpg",f="/apartment-renovation-new-jersey/assets/IMG_3555-8fe1b69d.jpg",M="/apartment-renovation-new-jersey/assets/IMG_3556-a8496d58.jpg",u="/apartment-renovation-new-jersey/assets/IMG_3557-bc802224.jpg",w=[{original:s,description:"Hokkaido Flower"},{original:o,description:"Container Haulage Freight"},{original:i,description:"Aerial Beach View"},{original:r,description:"Flower Blooms"},{original:g,description:"Alpine Mountains"},{original:c,description:"Mountain Lake Sailing"},{original:p,description:"Alpine Spring Meadows"},{original:l,description:"Nature Landscape"},{original:m,description:"Lighthouse Coast Sea"},{original:d,description:"Lighthouse Coast Sea"},{original:j,description:"Lighthouse Coast Sea"},{original:y,description:"Lighthouse Coast Sea"},{original:h,description:"Lighthouse Coast Sea"},{original:f,description:"Lighthouse Coast Sea"},{original:M,description:"Lighthouse Coast Sea"},{original:u,description:"Lighthouse Coast Sea"}],G=document.querySelector(".photos-gallery"),I=w.map(({original:e})=>`
    <li class="gallery-item">
	<a class="gallery-link" data-fancybox="gallery" href=${e}>
		<img 
			class="gallery-image" 
			src=${e} 
			alt=""
			/>
	</a>
    </li>
  `).join("");try{G.insertAdjacentHTML("beforeend",I)}catch{console.log("not a problem")}n.bind("[data-fancybox]",{loop:!0,animationEffect:"fade",hideScrollbar:!1,Carousel:{transition:"slide"},caption:function(e,t){var a;return((a=t.thumbEl)==null?void 0:a.alt)||""}});
//# sourceMappingURL=commonHelpers.js.map
